apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-ui-deployment
  namespace: ashwini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-ui
  template:
    metadata:
      labels:
        app: sample-ui
    spec:
      containers:
        - name: sample-ui-container
          image: ashwini939/sample-ui:latest  # Placeholder; will be replaced by sed in GitHub Actions
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: sample-ui-service
  namespace: ashwini
spec:
  selector:
    app: sample-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
